// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe3RZp9ZkBAerQ7TknzdNUOtKKoefYsfo',
    appId: '1:1010215667325:web:9d05a75a93d46b1048d314',
    messagingSenderId: '1010215667325',
    projectId: 'e-com-f0224',
    authDomain: 'e-com-f0224.firebaseapp.com',
    storageBucket: 'e-com-f0224.appspot.com',
    measurementId: 'G-GLTB26LZ6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAczUW4RV76sRPZMtf95hVvN1vEpHgGQqw',
    appId: '1:1010215667325:android:8f7aa12545d7084a48d314',
    messagingSenderId: '1010215667325',
    projectId: 'e-com-f0224',
    storageBucket: 'e-com-f0224.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRQZHfT-laJ3FZF9OC7DhCA4_Ob2lGrYs',
    appId: '1:1010215667325:ios:16b20f4a49be65e248d314',
    messagingSenderId: '1010215667325',
    projectId: 'e-com-f0224',
    storageBucket: 'e-com-f0224.appspot.com',
    androidClientId: '1010215667325-n4ligo9n24b7n2n80bkgup7bmmva2206.apps.googleusercontent.com',
    iosClientId: '1010215667325-hg1u94v55bltjuc1bo4qia47ood0ncbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRQZHfT-laJ3FZF9OC7DhCA4_Ob2lGrYs',
    appId: '1:1010215667325:ios:16b20f4a49be65e248d314',
    messagingSenderId: '1010215667325',
    projectId: 'e-com-f0224',
    storageBucket: 'e-com-f0224.appspot.com',
    androidClientId: '1010215667325-n4ligo9n24b7n2n80bkgup7bmmva2206.apps.googleusercontent.com',
    iosClientId: '1010215667325-hg1u94v55bltjuc1bo4qia47ood0ncbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );
}
